name: farmers_directory
description: Farmers directory app to connect users directly with farmer.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  dots_indicator: ^2.1.0
  get: ^4.6.5
  flutter_launcher_icons: ^0.10.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.6
  dropdown_button2: ^1.8.8
  http: ^0.13.5
  flutter_secure_storage: ^6.0.0

flutter_icons:
  android: true
  image_path: 'assets/images/logo.png'

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/logo.png

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    #         style: italic
    - family: Josefin Sans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
